/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_identity_pool_id": "ap-southeast-2:14ed7918-0b01-4833-9c0e-c0990aae2a07",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_fgYPdTbeo",
    "aws_user_pools_web_client_id": "13td7nuhrde7hlvbf5on06uj2j",
    "oauth": {}
};


export default awsmobile;
